"""Initial migration

Revision ID: 01d788a33bff
Revises:
Create Date: 2025-09-01 00:21:17.918626

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from src.core.database.custom_types import TZDateTime

# revision identifiers, used by Alembic.
revision: str = "01d788a33bff"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("additional_context", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id"),
    )
    op.create_table(
        "language_extraction_job_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "news_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "range_bucket_buy_order",
        sa.Column("start_price", sa.Float(), nullable=False),
        sa.Column("end_price", sa.Float(), nullable=False),
        sa.Column("num_buckets", sa.Integer(), nullable=True),
        sa.Column("bucket_size", sa.Float(), nullable=True),
        sa.Column("price_tolerance", sa.Float(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("stock_code", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("WAITING", "TRIGGERED", "COMPLETED", "CANCELLED", "ERROR", name="customorderstatus"), nullable=False),
        sa.Column("last_checked_price", sa.Float(), nullable=True),
        sa.Column("last_check_time", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trailing_stop_buy_order",
        sa.Column("max_price", sa.Float(), nullable=False),
        sa.Column("lowest_price", sa.Float(), nullable=False),
        sa.Column("trailing_amount", sa.Float(), nullable=True),
        sa.Column("trailing_percent", sa.Float(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("stock_code", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("WAITING", "TRIGGERED", "COMPLETED", "CANCELLED", "ERROR", name="customorderstatus"), nullable=False),
        sa.Column("last_checked_price", sa.Float(), nullable=True),
        sa.Column("last_check_time", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trailing_stop_sell_order",
        sa.Column("min_price", sa.Float(), nullable=False),
        sa.Column("highest_price", sa.Float(), nullable=False),
        sa.Column("trailing_amount", sa.Float(), nullable=True),
        sa.Column("trailing_percent", sa.Float(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("stock_code", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("WAITING", "TRIGGERED", "COMPLETED", "CANCELLED", "ERROR", name="customorderstatus"), nullable=False),
        sa.Column("last_checked_price", sa.Float(), nullable=True),
        sa.Column("last_check_time", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annotated_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.document_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "financial_news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("published", TZDateTime(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["news_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "language_extraction_examples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("job_type_id", sa.Integer(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_type_id"],
            ["language_extraction_job_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "price_bucket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("is_triggered", sa.Boolean(), nullable=False),
        sa.Column("trigger_time", TZDateTime(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["range_bucket_buy_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "extractions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("extraction_class", sa.String(), nullable=False),
        sa.Column("extraction_text", sa.String(), nullable=False),
        sa.Column("alignment_status", sa.Enum("MATCH_EXACT", "MATCH_GREATER", "MATCH_LESSER", "MATCH_FUZZY", name="alignmentstatus"), nullable=True),
        sa.Column("extraction_index", sa.Integer(), nullable=True),
        sa.Column("group_index", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("annotated_document_id", sa.Integer(), nullable=True),
        sa.Column("example_id", sa.Integer(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotated_document_id"],
            ["annotated_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["example_id"],
            ["language_extraction_examples.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "char_intervals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_pos", sa.Integer(), nullable=True),
        sa.Column("end_pos", sa.Integer(), nullable=True),
        sa.Column("extraction_id", sa.Integer(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["extraction_id"],
            ["extractions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("char_intervals")
    op.drop_table("extractions")
    op.drop_table("price_bucket")
    op.drop_table("language_extraction_examples")
    op.drop_table("financial_news")
    op.drop_table("annotated_documents")
    op.drop_table("trailing_stop_sell_order")
    op.drop_table("trailing_stop_buy_order")
    op.drop_table("range_bucket_buy_order")
    op.drop_table("news_sources")
    op.drop_table("language_extraction_job_types")
    op.drop_table("documents")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
