"""Updated column names from trailing orders

Revision ID: aa3ac52b05f4
Revises: 01d788a33bff
Create Date: 2025-09-02 01:03:58.442862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3ac52b05f4'
down_revision: Union[str, Sequence[str], None] = '01d788a33bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trailing_stop_buy_order', sa.Column('lowest_seen_price', sa.Float(), nullable=False))
    op.drop_column('trailing_stop_buy_order', 'lowest_price')
    op.add_column('trailing_stop_sell_order', sa.Column('highest_seen_price', sa.Float(), nullable=False))
    op.drop_column('trailing_stop_sell_order', 'highest_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trailing_stop_sell_order', sa.Column('highest_price', sa.FLOAT(), nullable=False))
    op.drop_column('trailing_stop_sell_order', 'highest_seen_price')
    op.add_column('trailing_stop_buy_order', sa.Column('lowest_price', sa.FLOAT(), nullable=False))
    op.drop_column('trailing_stop_buy_order', 'lowest_seen_price')
    # ### end Alembic commands ###
